# Generated by Django 3.0.10 on 2020-10-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='qualification',
        ),
    ]
