# Generated by Django 3.0.10 on 2020-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201024_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='alloted_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
