# Generated by Django 3.0.10 on 2020-10-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201029_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecine',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Appointment'),
        ),
    ]
