# Generated by Django 3.0.10 on 2020-10-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201029_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy'),
        ),
    ]
